services:
  - type: web
    name: sudhamrit-inventory-management
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: PGSSLMODE
        value: require
      - key: DATABASE_URL
        sync: false # Set this manually in Render dashboard
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health